# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default=0, max_length=10)),
                ('session', models.CharField(default=0, max_length=35)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default=0, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField()),
                ('belongs_to_cart', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherapp.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('confirmation', models.CharField(default=0, max_length=15)),
                ('delivery', models.IntegerField(blank=True, default=0, null=True)),
                ('orderName', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_cart', models.ForeignKey(blank=True, default=False, max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherapp.Cart')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=0, upload_to='')),
                ('name', models.CharField(help_text='What is The Name To Display For The Product?', max_length=255)),
                ('price', models.FloatField(help_text='Add The Price WITHOUT The $ Sign. Such As: 4.95 or 9.99')),
                ('keywords', models.CharField(help_text='Enter Keywords Seperated By Spaces Such As: chicken, rice, hot, peppers', max_length=255)),
                ('sizes', models.CharField(help_text='To Make Different Sizes Type: "Small,Medium,Large" Without Any Spaces', max_length=255)),
                ('featured', models.IntegerField(blank=True, default=0, help_text='Set This To 1 For It To Display on The Front Page', null=True)),
                ('description', models.TextField(max_length=1500)),
                ('excerpt', models.CharField(help_text='This is a Short Snippet Below Each Product', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryMin', models.DecimalField(decimal_places=2, help_text='What is the smallest dollar amount to be able to deliver?', max_digits=5)),
                ('tax', models.DecimalField(decimal_places=4, help_text='Tax as decimal (8.65% is 0.0865)', max_digits=5)),
                ('deliveryFee', models.DecimalField(decimal_places=2, help_text='How much is it additionally to deliver?', max_digits=5)),
                ('sKey', models.CharField(max_length=100)),
                ('site_title', models.CharField(blank=True, default='website title', help_text='What is the website called?', max_length=100, null=True)),
                ('site_description', models.CharField(blank=True, default='website description', help_text='Give a description seen in the stripe checkout modal.', max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotherapp.Product'),
        ),
    ]
