# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
