# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anotherapp', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, help_text='Choose a Category. If you would like to add a Category, go back and find the Category page', null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherapp.Category'),
        ),
    ]
