# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotherapp', '0005_auto_20160819_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='deliveryFee',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='How much is it additionally to deliver?', max_digits=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='deliveryMin',
            field=models.DecimalField(decimal_places=2, default=10, help_text='What is the smallest dollar amount to be able to deliver?', max_digits=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0863, help_text='Tax as decimal (8.65% is 0.0865)', max_digits=5),
        ),
    ]
